nodeLinker: pnp
yarnPath: .yarn/releases/yarn-3.3.1.cjs
packageExtensions:
  '@mantine/styles@*':
    dependencies:
      '@emotion/react': '>=11.10.5'
      '@emotion/cache': '>=11.10.5'
      '@emotion/utils': '>=1.2.0'
      '@emotion/serialize': '>=1.1.1'
