yarnPath: .yarn/releases/yarn-3.3.1.cjs
nodeLinker: node-modules
packageExtensions:
  'local-pkg@*':
    dependencies:
      'jsdom': '>=20.0.3'
  '@mantine/styles@*':
    dependencies:
      '@emotion/react': '>=11.10.5'
      '@emotion/cache': '>=11.10.5'
      '@emotion/utils': '>=1.2.0'
      '@emotion/serialize': '>=1.1.1'
  'storybook@*':
    dependencies:
      'react': '>=18.2.0'
      'react-dom': '>=18.2.0'

